services:
  - type: web
    name: ems-backend
    runtime: node
    rootDir: Ems-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
